#!/bin/bash
set -e

export SPARSE="system.img"
export RAW="system.raw.img"
export PATCHED="system.patched.img"
export MNTPOINT="/mnt/"
export DIFF="$(pwd)/Patches/dipper.patch"
export WORKDIR="$(pwd)"

if [ $UID -ne 0 ]; then
	echo ">>ERROR: Please run this script as root/sudo!"
	exit 1
fi


if [ hash apt 2>/dev/null ]; then # Debian
	apt install simg2img img2simg brotli patch python-is-python3 wget
elif [ hash dnf 2>/dev/null ]; then # Fedora
	dnf install brotli patch python-is-python3 simg2img img2simg wget
elif [ hash pacman 2>/dev/null ]; then # Arch Linux
	pacman -Sy brotli patch android-tools wget
elif [ hash zypper 2>/dev/null ]; then # openSUSE
	zypper install brotli patch android-tools wget
fi


if [ ! -e $SPARSE ]; then
	echo "ERROR: No system.img found! Put this script near system.img!"
	exit 1
fi

./patchsystem
./prepare-system-files
./create-zip

