#!/bin/bash
set -e

simg2img $SPARSE $RAW # Converting sparse system.img to raw ext4 system.raw.img
mount $RAW $MNTPOINT # Mount raw image

cd /
echo "Applying patch"
if ! patch -p1 < $DIFF; then
	echo ">> ERROR: Some system files are incompatible with the patches;
          Please adjust '$DIFF' and try again!"
	exit 1
fi
echo "Patch applied successfully!"

echo "Going back to $PWD"
cd - 
echo $(pwd)

umount $MNTPOINT
img2simg $PWD/$RAW $PATCHED
